import type { MetadataRoute } from "next"

export default function robots(): MetadataRoute.Robots {
  const baseUrl = "https://acquireandbuild.com"

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/_next/",
          "/favicon.ico",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
      {
        userAgent: "GPTBot",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
      {
        userAgent: "ChatGPT-User",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
      {
        userAgent: "CCBot",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
      {
        userAgent: "anthropic-ai",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
      {
        userAgent: "Claude-Web",
        allow: "/",
        disallow: [
          "/debug-datocms",
          "/debug-homepage",
          "/debug-newsletter",
          "/admin",
          "/api/",
          "/datocms-setup",
          "/deal-kit-setup",
          "/subscribers",
          "/lead-magnet-subscribers",
          "/deal-kit-analytics",
          "/manifest.webmanifest",
          "/*.webmanifest",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
